"""initial schema

Revision ID: 350eb06f22ae
Revises: 
Create Date: 2026-06-18 16:43:32.188720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350eb06f22ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('orders_cap', sa.Integer(), nullable=True),
    sa.Column('conversations_cap', sa.Integer(), nullable=True),
    sa.Column('stores_cap', sa.Integer(), nullable=True),
    sa.Column('universal_numbers_cap', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pool_numbers',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('flag', sa.String(length=8), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('assigned', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_pool_numbers_country_code'), 'pool_numbers', ['country_code'], unique=False)
    op.create_table('resellers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resellers_email'), 'resellers', ['email'], unique=True)
    op.create_table('ai_settings',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('ai_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('creativity', sa.Integer(), nullable=False),
    sa.Column('response_length', sa.String(length=16), nullable=False),
    sa.Column('primary_language', sa.String(length=32), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('always_sound_human', sa.Boolean(), nullable=False),
    sa.Column('upsell_aggressiveness', sa.Integer(), nullable=False),
    sa.Column('convince_hesitant', sa.Boolean(), nullable=False),
    sa.Column('fallback_to_human', sa.Boolean(), nullable=False),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reseller_id')
    )
    op.create_table('customers',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_reseller_id'), 'customers', ['reseller_id'], unique=False)
    op.create_table('meta_configs',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('pixel_id', sa.String(length=64), nullable=True),
    sa.Column('capi_access_token_enc', sa.Text(), nullable=True),
    sa.Column('test_event_code', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reseller_id')
    )
    op.create_table('pool_assignments',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('pool_number_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_number_id'], ['pool_numbers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_assignments_pool_number_id'), 'pool_assignments', ['pool_number_id'], unique=False)
    op.create_index(op.f('ix_pool_assignments_reseller_id'), 'pool_assignments', ['reseller_id'], unique=True)
    op.create_table('products',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_description', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_reseller_id'), 'products', ['reseller_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('templates',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta_template_name', sa.String(length=120), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_reseller_id'), 'templates', ['reseller_id'], unique=False)
    op.create_table('usages',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=False),
    sa.Column('cycle_end', sa.Date(), nullable=False),
    sa.Column('orders_used', sa.Integer(), nullable=False),
    sa.Column('conversations_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usages_reseller_id'), 'usages', ['reseller_id'], unique=False)
    op.create_table('whatsapp_configs',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('number_type', sa.String(length=16), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reseller_id')
    )
    op.create_table('click_sessions',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('ref_token', sa.String(length=16), nullable=False),
    sa.Column('src_platform', sa.String(length=16), nullable=False),
    sa.Column('fbclid', sa.String(length=255), nullable=True),
    sa.Column('fbp', sa.String(length=255), nullable=True),
    sa.Column('fbc', sa.String(length=255), nullable=True),
    sa.Column('ttclid', sa.String(length=255), nullable=True),
    sa.Column('sclid', sa.String(length=255), nullable=True),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('utm_source', sa.String(length=64), nullable=True),
    sa.Column('utm_medium', sa.String(length=64), nullable=True),
    sa.Column('utm_campaign', sa.String(length=120), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('matched_chat_id', sa.String(length=32), nullable=True),
    sa.Column('add_to_cart_sent', sa.Boolean(), nullable=False),
    sa.Column('add_to_cart_event_id', sa.String(length=64), nullable=True),
    sa.Column('purchase_event_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_sessions_ref_token'), 'click_sessions', ['ref_token'], unique=True)
    op.create_index(op.f('ix_click_sessions_reseller_id'), 'click_sessions', ['reseller_id'], unique=False)
    op.create_table('product_bundles',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_bundles_product_id'), 'product_bundles', ['product_id'], unique=False)
    op.create_table('product_options',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_options_product_id'), 'product_options', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('combo', sa.JSON(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('chats',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('click_session_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('unread', sa.Integer(), nullable=False),
    sa.Column('draft_items', sa.JSON(), nullable=True),
    sa.Column('wa_thread_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['click_session_id'], ['click_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_customer_id'), 'chats', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chats_reseller_id'), 'chats', ['reseller_id'], unique=False)
    op.create_index(op.f('ix_chats_wa_thread_id'), 'chats', ['wa_thread_id'], unique=False)
    op.create_table('messages',
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_table('orders',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.String(length=32), nullable=True),
    sa.Column('click_session_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('tracking_number', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('source_platform', sa.String(length=16), nullable=True),
    sa.Column('follow_up_template_id', sa.String(length=32), nullable=True),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_address', sa.JSON(), nullable=True),
    sa.Column('purchase_event_sent', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['click_session_id'], ['click_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follow_up_template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_code'), 'orders', ['code'], unique=True)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_reseller_id'), 'orders', ['reseller_id'], unique=False)
    op.create_table('attribution_events',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('click_session_id', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['click_session_id'], ['click_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_events_event_id'), 'attribution_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_attribution_events_reseller_id'), 'attribution_events', ['reseller_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.String(length=32), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_attribution_events_reseller_id'), table_name='attribution_events')
    op.drop_index(op.f('ix_attribution_events_event_id'), table_name='attribution_events')
    op.drop_table('attribution_events')
    op.drop_index(op.f('ix_orders_reseller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_wa_thread_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_reseller_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_customer_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_options_product_id'), table_name='product_options')
    op.drop_table('product_options')
    op.drop_index(op.f('ix_product_bundles_product_id'), table_name='product_bundles')
    op.drop_table('product_bundles')
    op.drop_index(op.f('ix_click_sessions_reseller_id'), table_name='click_sessions')
    op.drop_index(op.f('ix_click_sessions_ref_token'), table_name='click_sessions')
    op.drop_table('click_sessions')
    op.drop_table('whatsapp_configs')
    op.drop_index(op.f('ix_usages_reseller_id'), table_name='usages')
    op.drop_table('usages')
    op.drop_index(op.f('ix_templates_reseller_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_reseller_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pool_assignments_reseller_id'), table_name='pool_assignments')
    op.drop_index(op.f('ix_pool_assignments_pool_number_id'), table_name='pool_assignments')
    op.drop_table('pool_assignments')
    op.drop_table('meta_configs')
    op.drop_index(op.f('ix_customers_reseller_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_resellers_email'), table_name='resellers')
    op.drop_table('resellers')
    op.drop_index(op.f('ix_pool_numbers_country_code'), table_name='pool_numbers')
    op.drop_table('pool_numbers')
    op.drop_table('plans')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
