"""platform_settings singleton table

Revision ID: 485f10bb64d5
Revises: 32a88a156d8d
Create Date: 2026-06-27 16:35:17.757858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485f10bb64d5'
down_revision: Union[str, None] = '32a88a156d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('platform_name', sa.String(length=120), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=64), nullable=True),
    sa.Column('default_ai_name', sa.String(length=64), nullable=False),
    sa.Column('default_ai_tone', sa.String(length=32), nullable=False),
    sa.Column('default_response_length', sa.String(length=16), nullable=False),
    sa.Column('default_opening_message', sa.Text(), nullable=True),
    sa.Column('starter_chats_cap', sa.Integer(), nullable=False),
    sa.Column('growth_chats_cap', sa.Integer(), nullable=False),
    sa.Column('scale_chats_cap', sa.Integer(), nullable=True),
    sa.Column('pool_capacity_per_number', sa.Integer(), nullable=False),
    sa.Column('auto_escalate_after_msgs', sa.Integer(), nullable=False),
    sa.Column('ai_typing_delay_ms', sa.Integer(), nullable=False),
    sa.Column('wa_setup_video_url', sa.String(length=500), nullable=True),
    sa.Column('shopify_setup_video_url', sa.String(length=500), nullable=True),
    sa.Column('ai_training_video_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
