"""shopify_stores + products.shopify_store_id/shopify_product_id

Revision ID: 80e2aa14be47
Revises: c65a35dc604b
Create Date: 2026-06-27 14:22:17.587440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e2aa14be47'
down_revision: Union[str, None] = 'c65a35dc604b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_stores',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('shop_domain', sa.String(length=160), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('api_version', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('products_synced', sa.Integer(), nullable=False),
    sa.Column('orders_synced', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_stores_reseller_id'), 'shopify_stores', ['reseller_id'], unique=False)
    op.create_index(op.f('ix_shopify_stores_shop_domain'), 'shopify_stores', ['shop_domain'], unique=True)
    op.add_column('products', sa.Column('shopify_store_id', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('shopify_product_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_products_shopify_product_id'), 'products', ['shopify_product_id'], unique=False)
    op.create_index(op.f('ix_products_shopify_store_id'), 'products', ['shopify_store_id'], unique=False)
    op.create_foreign_key(None, 'products', 'shopify_stores', ['shopify_store_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_shopify_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_shopify_product_id'), table_name='products')
    op.drop_column('products', 'shopify_product_id')
    op.drop_column('products', 'shopify_store_id')
    op.drop_index(op.f('ix_shopify_stores_shop_domain'), table_name='shopify_stores')
    op.drop_index(op.f('ix_shopify_stores_reseller_id'), table_name='shopify_stores')
    op.drop_table('shopify_stores')
    # ### end Alembic commands ###
