"""ai_settings: add opening_message

Revision ID: 8a16de97e867
Revises: 485f10bb64d5
Create Date: 2026-06-28 13:23:12.692784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a16de97e867'
down_revision: Union[str, None] = '485f10bb64d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_settings', sa.Column('opening_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_settings', 'opening_message')
    # ### end Alembic commands ###
