"""subscriptions_credit_ledger_payments_plan_extend

Revision ID: ff95f04b1bf6
Revises: 8a16de97e867
Create Date: 2026-07-01 00:08:13.306901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff95f04b1bf6'
down_revision: Union[str, None] = '8a16de97e867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_reseller_id'), 'credit_ledger', ['reseller_id'], unique=False)
    op.create_table('payments',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tap_charge_id', sa.String(length=64), nullable=True),
    sa.Column('plan_code', sa.String(length=32), nullable=True),
    sa.Column('credits_granted', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_reseller_id'), 'payments', ['reseller_id'], unique=False)
    op.create_index(op.f('ix_payments_tap_charge_id'), 'payments', ['tap_charge_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('billing_cycle', sa.String(length=8), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('credits_granted_this_period', sa.Integer(), nullable=False),
    sa.Column('credits_used_this_period', sa.Integer(), nullable=False),
    sa.Column('tap_customer_id', sa.String(length=64), nullable=True),
    sa.Column('tap_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_reseller_id'), 'subscriptions', ['reseller_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.add_column('plans', sa.Column('price_annual', sa.Float(), nullable=False, server_default='0'))
    op.add_column('plans', sa.Column('monthly_credits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('plans', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('plans', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'sort_order')
    op.drop_column('plans', 'is_public')
    op.drop_column('plans', 'monthly_credits')
    op.drop_column('plans', 'price_annual')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reseller_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payments_tap_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reseller_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_credit_ledger_reseller_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    # ### end Alembic commands ###
